server:
  port: ${PORT:8865}
message: Configuración de Local en el servidor levantado!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    url: jdbc:mysql://localhost:3306/crudcloud?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      database-plataform: org.hibernate.dialect.MySQLDialect
  cloud:
    config:
      uri: http://localhost:8860
